info:
  title: Swagger Test App
  description: This is a sample server for a pet store.
  termsOfService: 'http://example.com/terms/'
  contact:
    name: API Support
    url: 'http://www.example.com/support'
    email: support@example.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.1
swagger: '2.0'
paths:
  /:
    get:
      description: Use to request all customers
      responses:
        '200':
          description: A successful response
  /status:
    get:
      description: Use to return all customers
    parameters:
      - name: customer
        in: query
        description: Name of our customer
        required: false
        type: string
        format: string
    responses:
      '200':
        description: Successfully created user
definitions: {}
responses: {}
parameters: {}
securityDefinitions: {}
tags: []

